//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoonRunner.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHNHANVIEN
    {
        public string MaNV { get; set; }
        public byte[] HinhNV { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
