//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoonRunner.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.ACCNHANVIENs = new HashSet<ACCNHANVIEN>();
            this.GIAOCAs = new HashSet<GIAOCA>();
            this.HOADONs = new HashSet<HOADON>();
            this.PHIEUBAOHANHs = new HashSet<PHIEUBAOHANH>();
            this.PHIEUNHAPHANGs = new HashSet<PHIEUNHAPHANG>();
        }
    
        public int MaNV { get; set; }
        public string HoNV { get; set; }
        public string TenNV { get; set; }
        public string GioiTinh { get; set; }
        public string SdtNV { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DiaChiNV { get; set; }
        public string CMND { get; set; }
        public string ChucVu { get; set; }
        public Nullable<int> Luong { get; set; }
        public int MaPB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCNHANVIEN> ACCNHANVIENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GIAOCA> GIAOCAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual HINHNHANVIEN HINHNHANVIEN { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUBAOHANH> PHIEUBAOHANHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUNHAPHANG> PHIEUNHAPHANGs { get; set; }
    }
}
