//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoonRunner.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUBAOHANH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEUBAOHANH()
        {
            this.CHITIETBAOHANHs = new HashSet<CHITIETBAOHANH>();
        }
    
        public string MaBH { get; set; }
        public string HoKH { get; set; }
        public string TenKH { get; set; }
        public Nullable<System.DateTime> NgayMuaHang { get; set; }
        public string MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETBAOHANH> CHITIETBAOHANHs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
